root: true
env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
globals:
  mxsdk: readonly
  $: readonly
  jQuery: readonly
  React: readonly
  ReactDOM: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion": 11
plugins:
  - react
rules:
  react/react-in-jsx-scope: "off"
  react/prop-types: "off"
settings:
  react:
    version: "16"
